// Date: 12/22/2019 6:22:30 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.huto.hutosmod.models;

import net.minecraft.client.model.ModelBiped;


import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
@SideOnly(Side.CLIENT)
public class ModelMysteriousMask2 extends ModelBiped
{
  //fields
    ModelRenderer LeftBand;
    ModelRenderer Mask;
    ModelRenderer BackBand;
    ModelRenderer RightBand;
  
  public ModelMysteriousMask2()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      LeftBand = new ModelRenderer(this, 80, 34);
      LeftBand.addBox(4F, -7F, -5F, 1, 1, 10);
      LeftBand.setRotationPoint(0F, 0F, 0F);
      LeftBand.setTextureSize(128, 64);
      LeftBand.mirror = true;
      setRotation(LeftBand, 0F, 0F, 0F);
      Mask = new ModelRenderer(this, 50, 34);
      Mask.addBox(-4F, -8F, -5F, 8, 8, 1);
      Mask.setRotationPoint(0F, 0F, 0F);
      Mask.setTextureSize(128, 64);
      Mask.mirror = true;
      setRotation(Mask, 0F, 0F, 0F);
      BackBand = new ModelRenderer(this, 50, 45);
      BackBand.addBox(-4F, -7F, 4F, 8, 1, 1);
      BackBand.setRotationPoint(0F, 0F, 0F);
      BackBand.setTextureSize(128, 64);
      BackBand.mirror = true;
      setRotation(BackBand, 0F, 0F, 0F);
      RightBand = new ModelRenderer(this, 80, 34);
      RightBand.addBox(-5F, -7F, -5F, 1, 1, 10);
      RightBand.setRotationPoint(0F, 0F, 0F);
      RightBand.setTextureSize(128, 64);
      RightBand.mirror = true;
      setRotation(RightBand, 0F, 0F, 0F);

      this.bipedHead.addChild(Mask);
      this.bipedHead.addChild(LeftBand);
      this.bipedHead.addChild(RightBand);
      this.bipedHead.addChild(BackBand);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
   // setRotationAngles(f, f1, f2, f3, f4, f5, entity);
/*    LeftBand.render(f5);
    Mask.render(f5);
    BackBand.render(f5);
    RightBand.render(f5);*/
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }
	public void renderMask(float par1, Entity entity){
	//	setRotationAngles(par1, par1, par1, par1, par1, par1, entity);
		LeftBand.render(par1);
		RightBand.render(par1);
		BackBand.render(par1);
		Mask.render(par1);
	}
}
